# Generated by Django 4.2.5 on 2024-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc4vp', '0002_organization_encrypted_sensitive_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
