# Generated by Django 4.2.5 on 2024-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oidc4vp', '0003_organization_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
