name: Django CI Pipeline

on:
  push:
    branches: 
      - main
      - release
      - testing-pipeline

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Check if Python is installed by default 
      run: |
        python3 -c "print('Hi')"

