# Generated by Django 4.2.5 on 2026-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webhook', '0002_token_active_token_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='hash',
            field=models.CharField(default='', max_length=355, verbose_name='Hash'),
        ),
    ]
