# Generated by Django 4.2.23 on 2026-09-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0019_remove_contextfile_schema_and_more'),
        ('webhook', '0003_token_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='allowed_dids',
            field=models.ManyToManyField(
                blank=True,
                help_text='Select the DIDs this token is permitted to use.',
                related_name='tokens',
                to='idhub.did',
                verbose_name='Allowed DIDs',
            ),
        ),
    ]
