# Generated by Django 4.2.23 on 2026-09-24 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('webhook', '0004_token_allowed_dids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
