# Generated by Django 4.2.5 on 2023-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificablecredential',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
