# Generated by Django 4.2.5 on 2023-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idhub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
    ]
