# Generated by Django 4.2.5 on 2024-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0002_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Web'), (2, 'Key')], verbose_name='Type'
            ),
        ),
    ]
