# Generated by Django 4.2.5 on 2023-11-14 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idhub', '0003_rol_description_alter_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrol',
            unique_together={('user', 'service')},
        ),
    ]
