# Generated by Django 4.2.5 on 2023-10-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idhub", "0004_userrol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="rol",
        ),
        migrations.AddField(
            model_name="service",
            name="rol",
            field=models.ManyToManyField(to="idhub.rol"),
        ),
    ]
