# Generated by Django 4.2.5 on 2024-06-13 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idhub', '0004_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_datas',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='file_datas',
            name='file_name',
            field=models.CharField(max_length=250, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file_datas',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='_description',
            field=models.CharField(
                db_column='description',
                max_length=250,
                null=True,
                verbose_name='Description',
            ),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='_name',
            field=models.TextField(db_column='name', null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='file_schema',
            field=models.CharField(max_length=250, verbose_name='Schema'),
        ),
        migrations.AlterField(
            model_name='verificablecredential',
            name='issued_on',
            field=models.DateTimeField(null=True, verbose_name='Issued on'),
        ),
        migrations.AlterField(
            model_name='verificablecredential',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Enabled'), (2, 'Issued'), (3, 'Revoked'), (4, 'Expired')],
                default=1,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='verificablecredential',
            name='type',
            field=models.CharField(max_length=250, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='verificablecredential',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vcredentials',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
