# Generated by Django 4.2.5 on 2024-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0005_alter_file_datas_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='did',
            name='ether_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='did',
            name='ether_privkey',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
