# Generated by Django 4.2.5 on 2025-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0005_alter_file_datas_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Web'), (2, 'Key'), (3, 'Web+Ether')], verbose_name='Type'
            ),
        ),
    ]
