# Generated by Django 4.2.5 on 2025-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0005_alter_file_datas_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCTemplatePdf',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('wkit_template_id', models.CharField(max_length=250)),
                ('data', models.TextField()),
            ],
        ),
    ]
