# Generated by Django 4.2.5 on 2023-10-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idhub", "0005_remove_service_rol_service_rol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schemas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_schema", models.CharField(max_length=250)),
                ("data", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
