# Generated by Django 4.2.5 on 2025-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0005_alter_file_datas_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCTemplatePdf',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('data', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
