# Generated by Django 4.2.5 on 2023-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0006_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_datas',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file_name', models.CharField(max_length=250)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
