# Generated by Django 4.2.5 on 2024-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0006_did_ether_address_did_ether_privkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='did',
            name='credential_as_issuer',
            field=models.TextField(null=True),
        ),
    ]
