# Generated by Django 4.2.5 on 2025-05-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0006_vctemplatepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificablecredential',
            name='template_pdf',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='idhub.vctemplatepdf',
            ),
        ),
    ]
