# Generated by Django 4.2.5 on 2025-06-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0008_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('key', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
