# Generated by Django 4.2.5 on 2025-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0009_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='context',
            field=models.CharField(max_length=250, null=True, verbose_name='Context'),
        ),
    ]
