# Generated by Django 4.2.5 on 2025-06-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0010_schemas_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.TextField(max_length=250)),
                ('file_name', models.CharField(max_length=250, unique=True)),
                (
                    'schema',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='context_file',
                        to='idhub.schemas',
                    ),
                ),
            ],
        ),
    ]
