# Generated by Django 4.2.23 on 2025-07-29 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0007_alter_event_type'),
        ('idhub', '0011_contextfile'),
    ]

    operations = []
