# Generated by Django 4.2.23 on 2025-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0011_contextfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vctemplatepdf',
            name='data',
            field=models.FileField(upload_to='pdftemplate/'),
        ),
        migrations.AlterField(
            model_name='vctemplatepdf',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
