# Generated by Django 4.2.23 on 2025-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0012_alter_did_type_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='did',
            name='is_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificablecredential',
            name='json_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
