# Generated by Django 4.2.23 on 2025-09-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0012_alter_did_type_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vctemplatepdf',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
