# Generated by Django 4.2.23 on 2025-08-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0013_did_is_product_verificablecredential_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificablecredential',
            name='subject_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
