# Generated by Django 4.2.23 on 2025-08-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0014_verificablecredential_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificablecredential',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
