# Generated by Django 4.2.23 on 2025-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0015_alter_verificablecredential_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='did',
            name='service_endpoint',
            field=models.CharField(
                blank=True, max_length=250, verbose_name='Service URI endpoint'
            ),
        ),
        migrations.AlterField(
            model_name='contextfile',
            name='file_name',
            field=models.CharField(max_length=250),
        ),
    ]
