# Generated by Django 4.2.23 on 2025-11-21 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0014_did_available_alter_event_type'),
        ('idhub', '0016_did_service_endpoint_alter_contextfile_file_name'),
    ]

    operations = []
