# Generated by Django 4.2.23 on 2026-04-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub', '0017_merge_20251121_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='validation_url',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='Validation URL'
            ),
        ),
    ]
