# Generated by Django 4.2.23 on 2026-08-19 00:03

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    VerificableCredential = apps.get_model('idhub', 'VerificableCredential')
    for row in VerificableCredential.objects.all():
        row.vc_id = uuid.uuid4()
        row.save(update_fields=['vc_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('idhub', '0018_schemas_validation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextfile',
            name='schema',
        ),

        migrations.AddField(
            model_name='verificablecredential',
            name='vc_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='verificablecredential',
            name='vc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        migrations.AlterField(
            model_name='verificablecredential',
            name='subject_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
