# Generated by Django 4.2.5 on 2024-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idhub_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
    ]
